# Generated by Django 4.1.6 on 2023-03-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='firstname',
        ),
        migrations.AlterField(
            model_name='car',
            name='died',
            field=models.CharField(max_length=255),
        ),
    ]
